//
//  USStates.swift
//  GasBuddyPro
//
//  Created by David on 11/21/23.
//

import Foundation

enum States: String, CaseIterable {
    case AK = "AK"
    case AL = "AL"
    case AR = "AR"
    case AZ = "AZ"
    case CA = "CA"
    case CO = "CO"
    case CT = "CT"
    case DE = "DE"
    case DC = "DC"
    case FL = "FL"
    case GA = "GA"
    case GU = "GU"
    case HI = "HI"
    case ID = "ID"
    case IL = "IL"
    case IN = "IN"
    case IA = "IA"
    case KS = "KS"
    case KY = "KY"
    case LA = "LA"
    case ME = "ME"
    case MD = "MD"
    case MA = "MA"
    case MI = "MI"
    case MN = "MN"
    case MS = "MS"
    case MO = "MO"
    case MT = "MT"
    case NE = "NE"
    case NV = "NV"
    case NH = "NH"
    case NJ = "NJ"
    case NM = "NM"
    case NY = "NY"
    case NC = "NC"
    case ND = "ND"
    case OH = "OH"
    case OK = "OK"
    case OR = "OR"
    case PA = "PA"
    case PR = "PR"
    case RI = "RI"
    case SC = "SC"
    case SD = "SD"
    case TN = "TN"
    case TX = "TX"
    case UT = "UT"
    case VT = "VT"
    case VI = "VI"
    case VA = "VA"
    case WA = "WA"
    case WV = "WV"
    case WI = "WI"
    case WY = "WY"
}
